version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_ADMIN_USERNAME=test
      - DEFAULT_ADMIN_EMAIL=test@test.com
      - DEFAULT_ADMIN_PASSWORD=test
    volumes:
      - ./backend/private_key.pem:/app/private_key.pem:ro
      - ./backend/public_key.pem:/app/public_key.pem:ro